apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fabric-app
spec:
  replicas: 1
  template:
    metadata:
      labels: 
        app: fabric-app 
    spec:
      containers:
      - name: ca-org1-example-com
        image: hyperledger/fabric-ca:x86_64-1.0.0
        ports:
        - containerPort: 7054
        - containerPort: 7054
      - name: orderer-example-com
        image: hyperledger/fabric-orderer:x86_64-1.0.0
        ports:
        - containerPort: 7050
        - containerPort: 7050
      - name: peer0-org1-example-com
        image: hyperledger/fabric-peer:x86_64-1.0.0
        ports:
        - containerPort: 7051
        - containerPort: 7051
        - containerPort: 7053
        - containerPort: 7053
      - name: couchdb
        image: hyperledger/fabric-couchdb:x86_64-1.0.0
        ports: 
        - containerPort: 5984 
        - containerPort: 5984 